### ISSUE TITLE
Error while running the file

### ISSUE THREAD

**Issue by Bamboozul** [lukearran/TvTimeToTrakt#18]
```
C:\Users\Administrator\Desktop\TvTimeToTrakt-main>python TimeToTrakt.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\TvTimeToTrakt-main\TimeToTrakt.py", line 65, in <module>
    config = getConfiguration()
  File "C:\Users\Administrator\Desktop\TvTimeToTrakt-main\TimeToTrakt.py", line 53, in getConfiguration
    data = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 31 (char 206)

C:\Users\Administrator\Desktop\TvTimeToTrakt-main>
```

**Comment by Sni3rs** [comment]
Hi, try to use double backslash on your config.json "GDPR_WORKSPACE_PATH" field. Like: C:\\Users\\Administrator\\Desktop\\YOUR-TVTIME-DATA-FOLDER
