### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by Drasila** [lukearran/TvTimeToTrakt#2]
Thank you for creating this useful tool. I tried using it and got this error:

>> What do you want to do?
    1) Import Watch History from TV Time
Enter your menu selection: 1
Traceback (most recent call last):
  File "/home/mr_4braham/transfer/TimeToTrakt.py", line 452, in <module>
    start()
  File "/home/mr_4braham/transfer/TimeToTrakt.py", line 440, in start
    processWatchedShows()
  File "/home/mr_4braham/transfer/TimeToTrakt.py", line 330, in processWatchedShows
    tvShowDateWatchedConverted = datetime.strptime(
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'episode_season_number' does not match format '%Y-%m-%d %H:%M:%S'

**Comment by lukearran** [comment]
Thanks,

This should be sorted now. Can you pull and try again please?

Luke

**Comment by Drasila** [comment]
I get a similar error now but with episode_id instead:

>> What do you want to do?
    1) Import Watch History from TV Time
Enter your menu selection: 1
Traceback (most recent call last):
  File "/home/mr_4braham/transfer/TimeToTrakt.py", line 452, in <module>
    start()
  File "/home/mr_4braham/transfer/TimeToTrakt.py", line 440, in start
    processWatchedShows()
  File "/home/mr_4braham/transfer/TimeToTrakt.py", line 330, in processWatchedShows
    tvShowDateWatchedConverted = datetime.strptime(
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'episode_id' does not match format '%Y-%m-%d %H:%M:%S'

**Comment by lukearran** [comment]
Sorry - I don't have my TV Time data anymore, so it's hard to test.

Could you provide me with a sample of your 'seen_episode.csv' and 'followed_tv_show.csv' data? If so, you can reach me privately at hello@lukearran.com

Kindest Regards

Luke

**Comment by Drasila** [comment]
Just sent them. Thank you.

**Comment by Drasila** [comment]
Hi. Have you been trying to figure it out what's going on with this issue?

**Comment by lukearran** [comment]
Sorry for the delay.

I've just pushed a commit with the index fields to match your sample import file. Can you try again?

Kindest Regards

Luke

**Comment by Drasila** [comment]
Hi. I pulled the new version and it worked just fine, thanks a lot.

Sincerely,
Abraao

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
