### ISSUE TITLE
Error when importing is done "UnicodeDecodeError: 'charmap' codec can't decode byte 0x81"

### ISSUE THREAD

**Issue by unleashed7** [lukearran/TvTimeToTrakt#36]
None of the shows I had to choose the correct version was marked. Was that supposed to happen after it finished with everything? Is this error why that never happened?

```
...
2023-11-30 06:49:55 [   INFO] :: (99.92%) - Processing 'Twisted Metal' Season 1 / Episode 8
2023-11-30 06:49:55 [   INFO] :: 'Twisted Metal Season 1, Episode 8' marked as seen
2023-11-30 06:49:56 [   INFO] :: (99.95%) - Processing 'Twisted Metal' Season 1 / Episode 9
2023-11-30 06:49:57 [   INFO] :: 'Twisted Metal Season 1, Episode 9' marked as seen
2023-11-30 06:49:58 [   INFO] :: (99.97%) - Processing 'Twisted Metal' Season 1 / Episode 10
2023-11-30 06:49:59 [   INFO] :: 'Twisted Metal Season 1, Episode 10' marked as seen
Traceback (most recent call last):
  File "C:\Users\u\Downloads\tvtime import\TvTimeToTrakt-main\TvTimeToTrakt-main\TimeToTrakt.py", line 164, in <module>
    start()
  File "C:\Users\u\Downloads\tvtime import\TvTimeToTrakt-main\TvTimeToTrakt-main\TimeToTrakt.py", line 158, in start
    process_watched_movies()
  File "C:\Users\u\Downloads\tvtime import\TvTimeToTrakt-main\TvTimeToTrakt-main\TimeToTrakt.py", line 100, in process_watched_movies
    watched_list = [row["movie_name"] for row in reader if row["type"] == "watch"]
  File "C:\Users\u\Downloads\tvtime import\TvTimeToTrakt-main\TvTimeToTrakt-main\TimeToTrakt.py", line 100, in <listcomp>
    watched_list = [row["movie_name"] for row in reader if row["type"] == "watch"]
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\csv.py", line 111, in __next__
    row = next(self.reader)
  File "C:\Users\u\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5008: character maps to <undefined>
```

**Comment by tezma90** [comment]
It moved on to the tracked movies, this error happened to me too.
