### ISSUE TITLE
Invalid \escape: line 4 column 31 (char 206)

### ISSUE THREAD

**Issue by L4UR3NS** [lukearran/TvTimeToTrakt#39]
Hello,

I am getting the following error message:

C:\Users\USERNAME\Downloads\TvTimeToTrakt-main>python TimeToTrakt.py
Traceback (most recent call last):
  File "C:\Users\USERNAME\Downloads\TvTimeToTrakt-main\TimeToTrakt.py", line 65, in <module>
    config = get_configuration()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\Downloads\TvTimeToTrakt-main\TimeToTrakt.py", line 47, in get_configuration
    data = json.load(f)
           ^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 31 (char 206)

**Comment by L4UR3NS** [comment]
Solved by changing all \'s in the config.json GDPR_WORKSPACE_PATH to /'s
