### ISSUE TITLE
ValueError: time data '50663409-12-05 02:20:00' does not match format '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by Tha14** [lukearran/TvTimeToTrakt#55]
```
2024-06-09 00:58:21 [INFO] :: 'The Wire Season 3, Episode 10' marked as seen
Traceback (most recent call last):
  File "C:\TvTimeToTrakt-main\TimeToTrakt.py", line 170, in <module>
    start()
  File "C:\TvTimeToTrakt-main\TimeToTrakt.py", line 155, in start
    process_watched_shows(WATCHED_SHOWS_PATH)
  File "C:\TvTimeToTrakt-main\TimeToTrakt.py", line 98, in process_watched_shows
    tv_time_show = TVTimeTVShow(row)
                   ^^^^^^^^^^^^^^^^^
  File "C:\TvTimeToTrakt-main\searcher.py", line 108, in __init__
    super().__init__(row["series_name"], row["created_at"])
  File "C:\TvTimeToTrakt-main\searcher.py", line 101, in __init__
    self.date_watched = datetime.strptime(
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\AppData\Local\Programs\Python\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '50663409-12-05 02:20:00' does not match format '%Y-%m-%d %H:%M:%S'
```

This is on the latest commit you just made. Script was working fine for the most part.

**Comment by Tha14** [comment]
> When did you request and receive your data? It looks like you’ve still got the old data, the date **50663409-12-05 02:20:00** isn’t correct. TvTime have fixed this recently so you may need to request your data again.

Ok, I was not aware. Thanks.
